export enum NOTIFICATION_TYPES {
    RECEIVED_NOTIFICATION="RECEIVED_NOTIFICATION",
    RECEIVED_PROGRAM="RECEIVED_PROGRAM",
    BOOKING_REQUEST="BOOKING_REQUEST",
    PACK_INVITE="PACK_INVITE",
    RECEIVED_PACK_PROGRAM_OFFER_INVITE="RECEIVED_PACK_PROGRAM_INVITE",
    PACK_PROGRAM_ACCEPTED="PACK_PROGRAM_STARTED",
    NEW_VLOG_COMMENT="NEW_VLOG_COMMENT"
}

Object.freeze(NOTIFICATION_TYPES)
