export enum NOTIFICATION_TYPES {
    RECEIVED_NOTIFICATION="RECEIVED_NOTIFICATION",
    RECEIVED_PROGRAM="RECEIVED_PROGRAM",
    BOOKING_REQUEST="BOOKING_REQUEST",
    PACK_INVITE="PACK_INVITE",
}

Object.freeze(NOTIFICATION_TYPES)
