//User reducer action types
export const UPDATE_CURRENT_USER_ATTRIBUTE_ACTION = 'UPDATE_CURRENT_USER_ATTRIBUTE';

export const UPDATE_CURRENT_USER_ACTION = 'UPDATE_CURRENT_USER';

//Packs reducer action types
export const UPDATE_CURRENT_USER_PACKS_ACTION = 'UPDATE_CURRENT_USER_PACKS';

export const REMOVE_CURRENT_USER_PACK = "REMOVE_CURRENT_USER_PACK";

export const ADD_CURRENT_USER_PACK = "ADD_CURRENT_USER_PACK";

//Programs reduer action types
export const ADD_CURRENT_USER_PROGRAM_ACTION = "ADD_CURRENT_USER_PROGRAM";

export const DELETE_CURRENT_USER_PROGRAM_ACTION = "DELETE_CURRENT_USER_PROGRAM"

export const UPDATE_CURRENT_USER_PROGRAMS_ACTION="UPDATE_CURRENT_USER_PROGRAMS";

export const ADD_WORKOUT_TO_PROGRAM_ACTION="ADD_WORKOUT_TO_PROGRAM"

//Workouts reducer action types
export const UPDATE_LUPA_WORKOUTS_ACTION="UPDATE_LUPA_WORKOUTS";

//Assessment reducer action types
export const UPDATE_LUPA_ASSESSMENTS_ACTION="UPDATE_LUPA_ASSESSMENTS"