//User reducer action types
export const UPDATE_CURRENT_USER_ATTRIBUTE_ACTION = 'UPDATE_CURRENT_USER_ATTRIBUTE';

export const UPDATE_CURRENT_USER_ACTION = 'UPDATE_CURRENT_USER';

//Packs reducer action types
export const UPDATE_CURRENT_USER_PACKS_ACTION = 'UPDATE_CURRENT_USER_PACKS';

export const REMOVE_CURRENT_USER_PACK = "REMOVE_CURRENT_USER_PACK";

export const ADD_CURRENT_USER_PACK = "ADD_CURRENT_USER_PACK";