"use strict";
exports.__esModule = true;
var MODALITY;
(function (MODALITY) {
    MODALITY["METABOLIC"] = "metabolic";
    MODALITY["CALISTHENICS"] = "calisthenics";
    MODALITY["WEIGHTLIFTING"] = "weightlifting";
})(MODALITY = exports.MODALITY || (exports.MODALITY = {}));
var GOAL_PATHWAY_STRUCTURE_UID;
(function (GOAL_PATHWAY_STRUCTURE_UID) {
    GOAL_PATHWAY_STRUCTURE_UID["IMPROVE_STRENGTH_METABOLIC"] = "dj928933hfoifjf";
    GOAL_PATHWAY_STRUCTURE_UID["IMPROVE_STRENGTH_CALISTHENICS"] = "jf892h938n2f3hf39hf";
    GOAL_PATHWAY_STRUCTURE_UID["IMPROVE_STRENGTH_WEIGHTLIFTING"] = "93ukfof3h4f984hf32d";
    GOAL_PATHWAY_STRUCTURE_UID["IMPROVE_POWER_CALISTHENICS"] = "sdf89hef98jgr93odidg";
    GOAL_PATHWAY_STRUCTURE_UID["IMPROVE_POWER_WEIGHTLIFTING"] = "jf29fjf29jf2e09f22f";
    GOAL_PATHWAY_STRUCTURE_UID["IMPROVE_FLEXIBILITY_CALISTHENICS"] = "idj0ifje09fj0ef";
    GOAL_PATHWAY_STRUCTURE_UID["IMPROVE_FLEXIBILITY_WEIGHTLIFTING"] = "fg020kfefkijf893hf";
    GOAL_PATHWAY_STRUCTURE_UID["IMPROVE_STAMINA_CALISTHENICS"] = "jdf092uej0fh9f8grh";
    GOAL_PATHWAY_STRUCTURE_UID["IMPROVE_STAMINA_WEIGHTLIFTING"] = "0djf39efh9e8fhfd";
})(GOAL_PATHWAY_STRUCTURE_UID = exports.GOAL_PATHWAY_STRUCTURE_UID || (exports.GOAL_PATHWAY_STRUCTURE_UID = {}));
var GOAL_UID;
(function (GOAL_UID) {
    GOAL_UID["IMPROVE_STRENGTH"] = "sf928hf3928h0ie";
    GOAL_UID["IMPROVE_POWER"] = "hsf98h298fh2h38f";
    GOAL_UID["IMPROVE_FLEXIBILITY"] = "f0928thnf3028h3ff";
    GOAL_UID["IMPROVE_STAMINA"] = "d3928thd09320d8f";
})(GOAL_UID = exports.GOAL_UID || (exports.GOAL_UID = {}));
